name: buildpacks-action
description: 'Execute buildpacks CLI in GitHub Actions'
author: 'mamezou-tech'
branding:
  icon: 'chevron-right'
  color: 'purple'
inputs:
  image:
    description: 'Name of container image'
    required: true
  tag:
    description: 'Tag of container image'
    default: 'latest'
    required: false
  path:
    description: 'Path to target application'
    required: true
  builder:
    description: 'Builder to use'
    required: true
  buildpacks:
    description: 'Custom buildpacks to use'
    required: false
  env:
    description: 'Build-time environment variables'
    required: false
outputs:
  command:
    description: 'build command executed'

runs:
  using: 'docker'
  image: 'Dockerfile'
