name: buildpacks-action
description: 'Execute buildpacks CLI in GitHub Actions'
author: 'mamezou-tech'
branding:
  icon: 'chevron-right'
  color: 'purple'
inputs:
  image:
    description: 'Name of container image'
    required: true
  tag:
    description: 'Tag of container image'
    default: 'latest'
    required: false
  path:
    description: 'Path to target application, defaults to the current directory'
    default: '.'
    required: false
  builder:
    description: 'Builder to use'
    required: true
  buildpacks:
    description: 'Custom buildpacks to use'
    required: false
  env:
    description: 'Build-time environment variables'
    required: false
  env_files:
    description: 'Read build-time environment variables from these files'
    required: false
  publish:
    description: 'Publish the resulting image to the registry'
    required: false
  debug_mode:
    description: "Run in debug mode - only output command is set. Don't run the pack command"
    required: false

outputs:
  command:
    description: 'build command executed'

runs:
  using: 'docker'
  image: 'Dockerfile'
