name: buildpacks-action
description: 'Execute buildpacks CLI in GitHub Actions'
author: 'mamezou-tech'
branding:
  icon: 'arrow-right-circle'
  color: 'purple'
inputs:
  image:
    description: 'Name of container image'
    required: true
  tag:
    description: 'Tag of container image'
    default: 'latest'
    required: false
  path:
    description: 'Path to target application'
    required: true
  builder:
    description: 'Builder to use'
    required: true
  version:
    description: 'Version of pack CLI'
    required: false
    default: 'v0.11.0'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    VERSION: ${{ inputs.version }}
